### ISSUE TITLE
Review 2

### ISSUE THREAD

**Issue by yunusbahari** [galuhest/item-crud-go#3]
- Indentasi
  - https://github.com/galuhest/item-crud-go/blob/master/crud.go#L8
  - https://github.com/galuhest/item-crud-go/blob/master/crud.go#L68-L69
  - https://github.com/galuhest/item-crud-go/blob/master/crud.go#L153
- Code
  - https://github.com/galuhest/item-crud-go/blob/master/crud.go#L22
deklarasi interface ini kurang berguna, interface harusnya didefinisikan secara `lazy` saja, ketika package tersebut membutuhkan dependency yang bisa di abstraksi kedalam interface maka baru definisikan (biasanya minimal untuk penulisan test/penggunaan dependency storage yang dapat di-swap dengan storage lain asal mengikuti interface yang dibutuhkan) (bisa baca https://blog.chewxy.com/2018/03/18/golang-interfaces/)
  - https://github.com/galuhest/item-crud-go/blob/master/crud.go#L86
karena ini merupakan package yang digunakan sebagai dependency, jangan ngeraise panic seperti ini untuk setiap error, beritahu kenapa errornya dan kembalikan ke stack frame sebelumnya, supaya yang memanggil methodnya bisa tahu dan handle, kalau ada aplikasi yang saya pakai, terus tiba2 kirim panic tiap ada kesalahan akan susah untuk recover dan applikasinya menjadi tidak  resilience

**Comment by galuhest** [comment]
fixed in #4
